### ISSUE TITLE
Cannot use sift algorithm 

### ISSUE THREAD

**Issue by naitianz0222** [quickbirdstudios/opencv-android#11]
I try to use sift algorithm in the opencv 3.4.4 with contribution packages.
"implementation 'com.quickbirdstudios:opencv:3.4.4-contrib'"
But it report error:
E/cv::error(): OpenCV(3.4.4) Error: The function/feature is not implemented (This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library) in static cv::Ptr<cv::xfeatures2d::SIFT> cv::xfeatures2d::SIFT::create(int, int, double, double, double), file /build/3_4-contrib_pack-contrib-android/opencv_contrib/modules/xfeatures2d/src/sift.cpp, line 1207

**Comment by znicolasrs** [comment]
I'm not one of the creators and I don't know the build tools they used, but if they used cmake to generate this opencv's package for android, there is an option (-DOPENCV_ENABLE_NONFREE=ON) to enable the nonfree algorithms like sift and surf, if this option is not set, these algorithms will not be avaliable. I believe the solution is to rebuild the package with this option set, but it's something for the creators do.

**Comment by sellmair** [comment]
Hmm, thanks for raising awareness for this issue. I will talk back with my colleagues to check whether or not we can push a build with that option as well!

**Comment by jodrescher** [comment]
I'am also interested in this feature. Please add it.

**Comment by sellmair** [comment]
We thought about this and came to the conclusion, that we will not build "non-free" modules for legal reasons. If you need any advice on how to build this on your own, you can hit us up!

**Comment by zzxjl1** [comment]
Hi there, i would appreciate that if anyone can offer me  a totourial. Thanks!
