### ISSUE TITLE
How can include *.h and *.cpp file in cpp file

### ISSUE THREAD

**Issue by huy-t** [quickbirdstudios/opencv-android#14]
When I include openCV in normal way, I can access cpp and h file by using this config in CMakeLists.txt

include_directories(../../../../openCV410/native/jni/include)

and in my cpp file:

#include <opencv2/opencv.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc_c.h>

how can I use it when use you lib?

**Comment by iamareebjamal** [comment]
I don't think you can. aar contains compiled binaries, whereas you need source files which only exist in sdk. I maybe wrong though. I have no experience with NDK and native builds

**Comment by sellmair** [comment]
You can't access the native source files like when using our builds directly. What are you trying to do, maybe I can help you in another way?
