### ISSUE TITLE
Saliency contrib module is missing

### ISSUE THREAD

**Issue by RaimundWege** [quickbirdstudios/opencv-android#15]
Is there a reason why some modules are missing? I was looking for the [saliency module](https://github.com/opencv/opencv_contrib/tree/4.1.0/modules/saliency) in the android `opencv:4.1.0-contrib` but I can't find it.

**Comment by sellmair** [comment]
I think some special modules have requirements to the build environment that we can't fulfill. Help is welcome here, if anyone plans to build those 👍

**Comment by RaimundWege** [comment]
I can build it now with `cmake` and without any issues. But the process to setup `cmake` was painful. For now I'm building my own custom OpenCV 4.1.0 for arm7, arm64, x86 and x86_64. I had to go this way because our library needs also to be as small as possible. If you like you can close this issue now.
