### ISSUE TITLE
Implementing 'face' for android app

### ISSUE THREAD

**Issue by willemgrier** [quickbirdstudios/opencv-android#16]
**Issue 1:** face package not recognized in opencv:4.1.0
implementation 'com.quickbirdstudios:opencv:4.1.0'
implementation 'com.quickbirdstudios:opencv:4.1.0-contrib'

error: package org.opencv.face does not exist 
error: cannot find symbol class FaceRecognizer  

**Issue 2:** model.read() function not seeing file (returns null pointer error)
--> I am trying to read a saved YAML model and load it into my new FaceRecognizer object. 
--> The model is saved in the external files directory (is this the best option)
--> Does the 'read' function have the ability to read from this directory?

To account for Issue 1, using 3.4.1
implementation 'com.quickbirdstudios:opencv:3.4.1'
implementation 'com.quickbirdstudios:opencv:3.4.4-contrib'

String externalDir = getExternalFilesDir (Environment.getDataDirectory().getAbsolutePath()) .getAbsolutePath();
String modelPath = externalDir+"/model.yml";
FaceRecognizer model;
model.read(modelPath);

java.lang.NullPointerException: Attempt to invoke virtual method 'void org.opencv.face.FaceRecognizer.read(java.lang.String)' on a null object reference

**Comment by sellmair** [comment]
Please create separate GitHub issues for each "issue" next time 👍 

*Issue 1*: 
You should not implement both dependencies: 

```
implementation 'com.quickbirdstudios:opencv:4.1.0' // <--- not necessary
implementation 'com.quickbirdstudios:opencv:4.1.0-contrib'
```

Can you try, if that fixes your issue?


*Issue 2*: 
The sample snippet does show that you crate the `model` anywhere.

**Comment by willemgrier** [comment]
Removing the first dependency did not work. 
For creating the model, the constructors are protected. Is there a work-around for this issue?

FaceRecognizer model = new FaceRecognizer(long); // the constructor has protected access in "org.opencv.face.FaceRecognizer"

> Please create separate GitHub issues for each "issue" next time 👍
> 
> _Issue 1_:
> You should not implement both dependencies:
> 
> ```
> implementation 'com.quickbirdstudios:opencv:4.1.0' // <--- not necessary
> implementation 'com.quickbirdstudios:opencv:4.1.0-contrib'
> ```
> 
> Can you try, if that fixes your issue?
> 
> _Issue 2_:
> The sample snippet does show that you crate the `model` anywhere.

**Comment by sellmair** [comment]
I never worked with the FaceRegognizer API's so you might want to ask your questions on the official OpenCV forum. I am sure you can expect help relatively quickly.
