### ISSUE TITLE
Understanding the project structure

### ISSUE THREAD

**Issue by sybrin-innovations** [quickbirdstudios/opencv-android#17]
Hi,

I have managed to successfully add the package to one of my project and all seems well. I really appreciate the effort that went into creating this repo.

I would just like to understand how it works. For instance, for a test i downloaded the repo and manually added one of the openCV modules to my android project. Everything build find and I can find the openCV functions however when i run the project it keeps complaining about "No implementation found for openCV". I have added the following below.

if (!OpenCVLoader.initDebug())
   Log.e("OpenCv", "Unable to load OpenCV");
else
   Log.d("OpenCv", "OpenCV loaded");

So i was wondering are there additional packages that gets pulled when i just add the
 implementation 'com.quickbirdstudios:opencv:3.4.1' dependency. 

compared to just using the repo manually.

I hope the question is not to vague.

**Comment by sellmair** [comment]
Hey, if the question is still relevant: 
Would you mind posting the full stacktrace that is linked to "No implementation found for openCV". Also: Is "Unable to load OpenCV" printend?
In theory, I cannot see a reason why manually adding the project should behave differently. Would you mind sharing your build files with me?
