### ISSUE TITLE
Unable to fill rectangle

### ISSUE THREAD

**Issue by rostopira** [quickbirdstudios/opencv-android#19]
I'm trying to fill rectangle with white color
```java
Imgproc.rectangle(mat, new Point(left, top), new Point(right, bottom), new Scalar(255), -1);
```
This draws white border of rectangle
-1 is `CV_FILL` afaik
I'm using version 3.4.1

**Comment by sellmair** [comment]
This repository is just building OpenCV and providing the builds. Please post this issue to the official OpenCV issue tracker.
