### ISSUE TITLE
Explanation needed for loading "haarcascade_frontalface_alt.xml" classifiers into the android studio

### ISSUE THREAD

**Issue by litoco** [quickbirdstudios/opencv-android#21]
Hey, first of all thanks for this library. I was hopeless that I could successfully integrate opencv into android studio. But fortunately, I found this and now I have successfully added opencv into my project.
I am new to opencv and don't have any idea how to load "haarcascade_frontalface_alt.xml"  into the android studio. Although I have successfully created CascadeClassifier object and on calling obejct.load("haarcascade_frontalface_alt.xml") it returns false. Please help me with it.

**Comment by nasirky** [comment]
@litoco Thank you for taking interest in our repo. Can you please give the following information:

1. Where are you putting the xml file?
2. Why are you using object.load and not the CascadeClassifier constructor?

**Comment by nasirky** [comment]
@litoco I would now close this issue. Please feel free to open a new issue if you have any questions (please don't forget to answer the above questions when you report a new issue on the same topic).
