### ISSUE TITLE
Huge repo

### ISSUE THREAD

**Issue by friederbluemle** [quickbirdstudios/opencv-android#23]
I just stopped a fetch operation after downloading 300+MB (it was not finished yet). Checking the commit log here on GitHub I noticed more than half a million lines of code and lots of binaries were pushed with the latest commit on master (6294885)

    1,106 changed files with 692,519 additions and 80 deletions

Without knowing the exact details, I was wondering if a different solution is possible (i.e. declaring dependencies/downloading external sources/binaries from the original place etc)..? Since the commit has already been pushed to `master` it would require a force push to decrease the repo size again (which is not very nice on a public repo).

Just checking for possible solutions.
Thanks!

**Comment by nasirky** [comment]
@friederbluemle Thank you for taking interest in our repo. One way would be to perform a shallow clone. In the near future, there is nothing planned to take care of this issue, however, if you have any ideas, feel free to share.

**Comment by nasirky** [comment]
@friederbluemle  I would now close this issue.

**Comment by friederbluemle** [comment]
Sure, thanks @nasirky for getting back here and the suggestion! 👍
