### ISSUE TITLE
No implementation found for imread_1

### ISSUE THREAD

**Issue by badadin** [quickbirdstudios/opencv-android#24]
I get this:
`java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.imgcodecs.Imgcodecs.imread_1(java.lang.String) (tried Java_org_opencv_imgcodecs_Imgcodecs_imread_11 and Java_org_opencv_imgcodecs_Imgcodecs_imread_11__Ljava_lang_String_2)`

when trying to execute `Imgcodecs.imread( imagePath )` (org.opencv.imgcodecs.Imgcodecs)

Dependencies:
```
implementation files("../../4.1.0/opencv-4.1.0-contrib.aar")
implementation files("../../4.1.0/opencv-4.1.0-contrib-sources.jar")
```

Tried both:
`OpenCVLoader.initDebug()`
and
```
static
{
	System.loadLibrary( "opencv_java4" );
}
```

[The full example I tried to run](https://github.com/opencv/opencv_contrib/blob/3.4.2/modules/face/samples/Facemark.java)

**Comment by sellmair** [comment]
Does the same happen when using the jcenter artifacts?

**Comment by badadin** [comment]
> Does the same happen when using the jcenter artifacts?

Tried now with:
`implementation 'com.quickbirdstudios:opencv:4.1.0-contrib'`
the answer is yes, the same happening :(

**Comment by badadin** [comment]
It works with 3.4.4 version. Version 4.1.0 has strange size:

![image](https://user-images.githubusercontent.com/23579911/73251601-ae370380-41d2-11ea-8056-8675184a523a.png)

3.4.4 is 116 Mb and 4.1.0 is 74 Mb.
