### ISSUE TITLE
Why was MIPS removed in version 4?

### ISSUE THREAD

**Issue by jacobg** [quickbirdstudios/opencv-android#25]
I noticed that `mips` and `mips64` were removed in version 4. Why is that?

**Comment by nasirky** [comment]
@jacobg Because OpenCV 4.0 removed support for `mips` and `mips64`

**Comment by nasirky** [comment]
@jacobg I would now close this issue.

**Comment by jacobg** [comment]
@nasirky Thanks very much for your reply. Much appreciated.
