### ISSUE TITLE
Please add OpenCV 4.2.0 (with contrib packages)

### ISSUE THREAD

**Issue by fmatulic** [quickbirdstudios/opencv-android#26]
Thank you.

**Comment by Valby500** [comment]
Is it possible to make the latest version 4.3.0 with contrib instead of 4.2.0? SIFT and SURF have had their patent expired recently and this has been corrected according to the release notes.

**Comment by nasirky** [comment]
@fmatulic and @Valby500 : Thank you for your interest in our repo. It is on our TODO list and would be tackled soon.

**Comment by MohiuddinM** [comment]
@nasirky 4.3.0 is also out can you just add that instead of 4.2.0 (I think OP will also be fine with it)

**Comment by nasirky** [comment]
@MohiuddinM We are planning to support both 4.2.0 and 4.3.0.

**Comment by konovalov-k** [comment]
@nasirky Greetings! 
How can I inject contrib modules in OpenCV basic release?
Can you provide some link to tutorials or please help me understand the actions you did for this awesome build?)
(basic 4.1 OpenCV lib -> black box > lib with contrib 4.1 OpenCV lib)

**Comment by nasirky** [comment]
@konovalov-k We already have v4.1 of openCV with contributions. Please use the following to integrate in your android project:

` implementation 'com.quickbirdstudios:opencv:4.1.0-contrib'`

Please note that we just released v4.2.0 and 4.3.0

**Comment by nasirky** [comment]
@fmatulic @Valby500 @MohiuddinM 

We have just released v4.2.0 and v4.3.0 (with and without the contribs). Please see the README page for details.
