### ISSUE TITLE
Use OpenCV from Native (C++) Code

### ISSUE THREAD

**Issue by jeffreyfjohnson** [quickbirdstudios/opencv-android#27]
I have a C++ file for my Android project that uses OpenCV. Previously, I just imported all of OpenCV Java into my project as a local module, and used the library that way from my C++ file. I would like to use the Gradle dependency provided here, but I'm having trouble setting it up so that my C++ file can use OpenCV.

What do I need to do, either in my `build.gradle`, or `CMakeLists.txt` files to make this work?

**Comment by nasirky** [comment]
Hey @jeffreyfjohnson. Thank you for your interest in our repo and for posting your question. However, we would need more information before we are able to answer:

1. I assume that have a mix project (C++ & Java) which implies you are using the NDK?
2. Can you share a bare minimum project (with a setup similar to yours) that I can check out?

**Comment by nasirky** [comment]
@jeffreyfjohnson I would close this issue now. Please feel free to open a new issue if you still need help.

**Comment by critt** [comment]
#37 I opened a new issue about this with hopefully more detail
