### ISSUE TITLE
Camera crashes

### ISSUE THREAD

**Issue by forest-jj** [quickbirdstudios/opencv-android#29]
version: opencv:4.1.0-contrib 
Call the camera program to crash

**Comment by nasirky** [comment]
@forest-jj Can you please elaborate it more.

**Comment by forest-jj** [comment]
**
There is no extra complicated code, there will be problems when installed on the phone！**

`public class OpenCvActivity extends AppCompatActivity implements CameraBridgeViewBase.CvCameraViewListener2 {
    private CameraBridgeViewBase openCvCameraView;

    private static final String TAG = "OpenCvActivity";
    private Mat mRgba; //
    private Mat mGray;
  

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_opencv);

        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        openCvCameraView = (CameraBridgeViewBase) findViewById(R.id.javaCameraView);
        openCvCameraView.setCameraIndex(0); 
//        openCvCameraView.enableFpsMeter(); 
        openCvCameraView.setCvCameraViewListener(this);
    }


    @Override
    protected void onResume() {
        super.onResume();
        if (!OpenCVLoader.initDebug()) {
            Log.e(TAG, "OpenCV init error");
        }
        openCvCameraView.enableView();
    }`

**Comment by nasirky** [comment]
@forest-jj Can you try using OpenCV 4.0.0 to check if the crash still occurs? Can you also post a sample project that I can use to reproduce this issue?

**Comment by nasirky** [comment]
@forest-jj Can you try OpenCV 4.2.0 or 4.3.0 to see if this issue still occurs? I am closing this issue but feel free to open a new issue if there is the same issue with 4.2.0 or 4.3.0
