### ISSUE TITLE
OpenCV 3.4.5 and targetSDK

### ISSUE THREAD

**Issue by netcat88** [quickbirdstudios/opencv-android#3]
Hi!

Are you guys planning to update 3.4.4 to 3.4.5?
Do 3.4.4 + contrib and 4.0.1 support Pie?

Thanks! :)

**Comment by sellmair** [comment]
An update to 3.4.5 only planned if someone would request this. 
As to 3.4.4 + contrib: This is working on Pie 👍 
I did not yet test 4.0.1 on Pie, but I see no reason, why it would not work!
