### ISSUE TITLE
opencv give me black screen

### ISSUE THREAD

**Issue by amrkamal123** [quickbirdstudios/opencv-android#36]
i already implementation opencv 
and it initialize successfully but JavaCameraView give me black screen 

Mainfest
`    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
`

so pls someone help me with this issue

**Comment by nasirky** [comment]
I am closing this issue now. Please open a new one if the issue still persists.
