### ISSUE TITLE
Screen Orientation

### ISSUE THREAD

**Issue by KerronXR** [quickbirdstudios/opencv-android#38]
When i run an OpenCV (4.3.0) i have this orientation issue when the picture is always flipped 90deg to the left no matter what is the actual camera orientation. After storming the net i found out that everyone has it.

There seems to be a fix for it:

[https://gist.github.com/heaversm/63e8036af6a124aecf3b26898bd2a0ad#file-opencv-portait-camera-android-java](url)

Full explanation here: [https://heartbeat.fritz.ai/working-with-the-opencv-camera-for-android-rotating-orienting-and-scaling-c7006c3e1916](url)

Would you mind adding that? Or implementing something like that?

**Comment by nasirky** [comment]
@KerronXR An update: It is still in the pipeline for internal discussion. I will update you as soon as I can.

**Comment by RandGor** [comment]
> @KerronXR An update: It is still in the pipeline for internal discussion. I will update you as soon as I can.

Hello! I find out that 3.4.0 works but rotated, 4.1.0 works but rotated, 4.2.0+ are not working. Only black screen in the preview. How to remove 90 deg rotation? I'm searching the answer for 4 days but there are no answer. I guess the best way is to ask the developers, isn't it? :)

**Comment by nasirky** [comment]
@RandGor @KerronXR Due to the holidays, I was not able to look into this. However, I will try to get a concrete answer for you before end of next week. Sorry for the inconvenience.

**Comment by nasirky** [comment]
I would close this issue now but in case the issue still persist, feel free to open a new issue.
