### ISSUE TITLE
Gradle Package too heavy

### ISSUE THREAD

**Issue by fdegarne** [quickbirdstudios/opencv-android#42]
Hi,

I dowloaded via gradle the 4.3.0 package and first of all, good job guys !

I just have a little issue.
With this package my apk is overweighted (20Mo before to 130Mo now).
I wonder if there's any way to exclude packages i don't need (or include only those i need) via gradle ?
For instance I just need those 5 packages : 

`import org.opencv.core.Mat;
import org.opencv.core.Size;
import org.opencv.core.Core;
import org.opencv.imgproc.Imgproc;
import org.opencv.android.Utils;`

Thanks for your attention.
Best regards,
Fabien

**Comment by nasirky** [comment]
@fdegarne Sorry for taking some time to get back to you. 

One way would be to use Gradle's `exclude` to exclude any packages that you don't need. Another way would be to compile opencv from source with just these packages included.

**Comment by duchieu1307** [comment]
> exclude any packages that you do

Hi @nasirky ,
Could you describe more detail, how to compile opencv from source with only needed mudule?
In my particular case, I need to use only Ximgproc.thinning(src, src);
Thanks

**Comment by nasirky** [comment]
@duchieu1307 I will soon share a link on how to do it yourself.

**Comment by ksxkq** [comment]
> @duchieu1307 I will soon share a link on how to do it yourself.

Could you tell me where the link is？

**Comment by Balasnest** [comment]
@nasirky I am also facing the same problem. Could you please help us to manage the size constraints?

**Comment by Balasnest** [comment]
@nasirky I am in need of help as I have a time constraint to release.  

Tried excluding from Gradle. But didn't work.
```
implementation ('com.quickbirdstudios:opencv:3.4.1') {
        exclude group: 'org.opencv', module: 'video'
        exclude group: 'org.opencv', module: 'calib3d'
        exclude group: 'org.opencv', module: 'ml'
        exclude group: 'org.opencv', module: 'features2d'
        exclude group: 'org.opencv', module: 'objdetect'
        exclude group: 'org.opencv', module: 'photo'
    }
```
Would appreciate it if I get any quick resolution or proposals to this. Otherwise have to plan for dynamic feature integration. Waiting for your reply!

**Comment by ksxkq** [comment]
> @duchieu1307 I will soon share a link on how to do it yourself.

👀

**Comment by nasirky** [comment]
@Balasnest Sorry for all the delays. I will get back to you definitely in the next 1-2 weeks.

**Comment by mbalyaba** [comment]
As a temporary solution, we can use android abi filters
`    defaultConfig {
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }	`
i my case, with abi filters apk size has been reduced from 158Mb to 55Mb. Hope it helps someone.

**Comment by nasirky** [comment]
Since @mbalyaba provided a solution to filter out unwanted Abis, I would close this issue.

**Comment by amarendra** [comment]
@nasirky well that just limits removal of other archs from a build. I guess what people might be interested in knowing is generating smaller .so files limited to only features that are needed from the open cv lib instead of a full .so.
