### ISSUE TITLE
face module missing from 4.0.1?

### ISSUE THREAD

**Issue by jacobg** [quickbirdstudios/opencv-android#5]
It looks like the face module is missing from the 4.0.1 package. Here is the Javadoc for it:
https://docs.opencv.org/4.0.1/javadoc/org/opencv/face/Face.html

Am I misunderstanding something?

**Comment by jacobg** [comment]
It looks like the face module is in a separate opencv_contrib project for "extra modules":
https://github.com/opencv/opencv_contrib/tree/master/modules/face

It would be nice to have a maven artifact for that.

**Comment by jacobg** [comment]
Looks like there's an opencv contrib on maven for 3.4.4:
https://mvnrepository.com/artifact/com.quickbirdstudios/opencv/3.4.4-contrib.

Would be nice to build one for 4.0.1.

**Comment by sellmair** [comment]
@jacobg We are planning to build and package version 4.1.0 in the next month. Would this version work for you?

**Comment by jacobg** [comment]
@sellmair That will be great! Thanks so much!

**Comment by sellmair** [comment]
Version 4.1.0 is now build and pushed to jCenter! 
We are trying to build it with contrib packages somewhere next week 👍

**Comment by srugea** [comment]
are you planning to also introduce Stitcher? it seems to be in the main package
thank you

**Comment by sellmair** [comment]
Version 4.1.0 with contribution packages is now online. Face module is included!
