### ISSUE TITLE
Use MavenCentral as JCenter will be sunset

### ISSUE THREAD

**Issue by VincentJoshuaET** [quickbirdstudios/opencv-android#54]

**Comment by nasirky** [comment]
@VincentJoshuaET This is currently in progress and will be done soon. Thank you for the reminder 😄

**Comment by Hamahmi** [comment]
@nasirky Has it been added to MavenCentral yet?

**Comment by nasirky** [comment]
@Hamahmi We are hoping to have migrated by end of next week

**Comment by AbdulinRuslan** [comment]
@nasirky Has it been added to MavenCentral yet? :)

**Comment by nasirky** [comment]
@AbdulinRuslan It is in progress :). Would hopefully be complete in the next few days.

**Comment by AbdulinRuslan** [comment]
@nasirky I hope so. Waiting for migration <3

**Comment by nasirky** [comment]
We are actively working on it @AbdulinRuslan :)

**Comment by nasirky** [comment]
@AbdulinRuslan @Hamahmi @VincentJoshuaET We have just released 4.5.3 via MavenCentral. Other versions are next in line. Please go through the README file on how to integrate it.

**Comment by Hamahmi** [comment]
@nasirky what about `3.4.5` ?

**Comment by nasirky** [comment]
@Hamahmi 3.4.5 is not currently in our list. However, if you want to request 3.4.5, you can do it under https://github.com/quickbirdstudios/opencv-android/issues/57

**Comment by nasirky** [comment]
@Hamahmi 3.4.5 will be released some time in the next 2 weeks.

I am now closing this issue as the migration to MavenCentral is complete. Thank you for your patience.
