### ISSUE TITLE
Request for OpenCV Versions

### ISSUE THREAD

**Issue by nasirky** [quickbirdstudios/opencv-android#57]
In case you need a certain OpenCV version, please write it down as a comment to this issue.

**Comment by AbdulinRuslan** [comment]
Hi @nasirky, it will be great if you migrate 3.4.1 version of opencv lib <3

Ty in advance!

**Comment by LeiStoneLi** [comment]
Hello,
it will be great if you could add 4.5.1 version.
I was wondering if you guys could add the compile files to the github project, just like the version opencv4_1_0、opencv4_1_0_contrib、opencv4_2_0、opencv4_2_0_contrib、opencv4_3_0、opencv4_3_0_contrib in this github project?
Thank you and have a nice day :)

**Comment by nasirky** [comment]
@LeiStoneLi Both 4.5.1 and the sharing of the compiled project is work in progress. 4.5.1 should be available soon while the compiled project will be released until end of next week

**Comment by nasirky** [comment]
@LeiStoneLi 4.5.1 has been released.

**Comment by Hamahmi** [comment]
`3.4.5`


also, thank you for the great effort

**Comment by nasirky** [comment]
@Hamahmi 3.4.5 has also been released and is available via MavenCentral.
