### ISSUE TITLE
Version 4.5.3 not working

### ISSUE THREAD

**Issue by ahmetturk** [quickbirdstudios/opencv-android#58]
`OpenCVLoader.initDebug()` successfully works in versions 4.3.0, 4.4.0, 4.5.0, 4.5.1, 4.5.2.
But it throws an error in version 4.5.3.
The error is `java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_info.so" not found`

**Comment by nasirky** [comment]
@ahmetturk we are aware of this issue but for us it happens in Android 10 but not 11. Can you please share which version does it not work for you? Also are you using the normal one or the one with contributions?

We have already a ticket open at MavenCentral to rewrite the versions

**Comment by nasirky** [comment]
@ahmetturk The artefacts on MavenCentral cannot be overwritten so we will release a new 4.5.3 version with the fix.

**Comment by nasirky** [comment]
@ahmetturk Can you please try the recently released version: `4.5.3.0`

**Comment by nasirky** [comment]
@ahmetturk I will close this issue now. In case 4.5.3.0 doesn't work for you, can you please start a new issue?
