### ISSUE TITLE
Add android x_86 and change minSdkVersion

### ISSUE THREAD

**Issue by talregev** [quickbirdstudios/opencv-android#6]
Why set [minSdkVersion][1] to 21?   
Can you set it to 10 or without? because I want to support older devices.    
Can you add android x_86  (32 and 64) binary also to support full devices?     
Thanks!   

[1]:https://github.com/quickbirdstudios/opencv-android/blob/master/opencv4_0_1/build.gradle#L38

**Comment by sellmair** [comment]
Hey @talregev 
it seems like OpenCV decided to bump the minSdkVersion on that one. I suggest you making a ticket on their side, since this repository is just building/packaging and distributing their sources, without changes! 
Otherwise, version 3.4.4 has a minSdkVersion of 14. Currently we are also using this version internally for a big project.

I will have a look at the targets (x_86) soon and will keep you updated on that one!

**Comment by talregev** [comment]
Thanks for your respond. I download opencv sdk for android, and they already compile all android version (arm, arm64, x86, x86_64). include share object (.so) and static (.a) library. 
I change the java to opencv,
I write a build.gradle file,  and copy the (.so) to libs and add it as jni files. 
If you want I can share you with my work. 
I wish there will be an official (or good unofficial) maven repo that will include this library. 
Thanks again for your work :)

**Comment by sellmair** [comment]
Sure just send as a PR or a link to your repository!

**Comment by sellmair** [comment]
Also, I share your wish. I think the infrastructure of OpenCV is not good at all. I do not get, why they are not pushing those artifacts to a repository!

**Comment by talregev** [comment]
It part from a project I was write. 
I am the author of [cv_bridge java][2]. (convert from ROS messages to opencv images and vice versa).

> Also, I share your wish. I think the infrastructure of OpenCV is not good at all. I do not get, why they are not pushing those artifacts to a repository!

I am not sure why. there already [ticket][1] open on their repo.
It really easy to create the android library after you download the sdk. 

[1]:https://github.com/opencv/opencv/issues/4588
[2]:https://github.com/talregev/android_cv_bridge

**Comment by talregev** [comment]
I just look and i see the libs folder is missing. I will correct it.

**Comment by talregev** [comment]
I upload the missing .so files into libs folder, under opencv folder.
