### ISSUE TITLE
Where can I download the source code?

### ISSUE THREAD

**Issue by quzn** [quickbirdstudios/opencv-android#61]
"Download the source from your desired release"
Where can I download the source code? 
Such 4.5.3.0, Thanks~

**Comment by neilyoung** [comment]
Oh shit. No answer. Having the same question 3 months later :)

**Comment by nasirky** [comment]
@quzn @neilyoung Sorry for all the delays. We wanted to upload the sources but it has been quite busy. We will try to upload them until end of April.

**Comment by neilyoung** [comment]
No problem, solved it since months

**Comment by nasirky** [comment]
Sources for 3.4.X uploaded (check releases). 4.X.X is next

**Comment by nasirky** [comment]
Please see https://github.com/quickbirdstudios/opencv-android/issues/68
