### ISSUE TITLE
Stitcher class missing?

### ISSUE THREAD

**Issue by cristianoccazinsp** [quickbirdstudios/opencv-android#62]
Looks like the Java interface does not have all of the OpenCV features, any work around it?

**Comment by nasirky** [comment]
Since Java Interface uses the C++ implementations, one idea would be to write methods in the JNI file that call the correct C++ methods and then use them.

**Comment by nasirky** [comment]
I am going to close this issue. Can you please create a new issue in case you are still facing this issue.
