### ISSUE TITLE
Does this opencv-android implementation include ffmpeg?

### ISSUE THREAD

**Issue by joram56** [quickbirdstudios/opencv-android#64]
Trying to write to a test video file using video writer as below:

```
videoWriter = new VideoWriter("test.avi", VideoWriter.fourcc('x', '2','6','4'),
                fps, frameSize, true);
```
results in the following error:
```
E/cv::error(): OpenCV(4.5.3) Error: Bad argument (CAP_IMAGES: can't find starting number (in the name of file): test.avi) in icvExtractPattern, file /home/quickbirdstudios/opencv/releases/opencv-4.5.3/modules/videoio/src/cap_images.cpp, line 253
```

I have read up about it and it seems to happen if opencv was built without ffmpeg. Is that the case for this project?

**Comment by nasirky** [comment]
I don't think OpenCV has FFMPEG as a dependency or module. OpenCV expects FFMPEG to be installed on the host machine.

**Comment by nasirky** [comment]
Closing this issue. Please feel free to open a new issue in case you need any help.
