### ISSUE TITLE
WechatQR Crashes for other language 

### ISSUE THREAD

**Issue by dineshkandan** [quickbirdstudios/opencv-android#65]
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0x82
    java_vm_ext.cc:578]     string: 'This is a Test ��f'
    java_vm_ext.cc:578]     input: '0x54 0x68 0x69 0x73 0x20 0x69 0x73 0x20 0x61 0x20 0x54 0x65 0x73 0x74 0x20 <0x82> 0xf1 0x8b 0x66'
    java_vm_ext.cc:578]     in call to NewStringUTF
    java_vm_ext.cc:578]     from java.util.List org.opencv.wechat_qrcode.WeChatQRCode.detectAndDecode_0(long, long, long
![MicrosoftTeams-image (48)](https://user-images.githubusercontent.com/85552628/154214713-46bc2c08-739e-497a-99f3-1fcda027a977.png)
)

**Comment by Sathishobs** [comment]
Hi @dineshkandan  I'm also facing similar issue and my app crashes frequently,. I was not able to catch the exception too to handle it. 

@nasirky @sellmair @maltebucksch Any code update on issue posted above? Could you guys please assist us how to overcome this blocker and run smooth scanning?

**Comment by nasirky** [comment]
@dineshkandan  @Sathishobs Can you please specify which version of OpenCV are you using?

The error seems like there is non UTF-8 data. Can you try a different code?

**Comment by nasirky** [comment]
I will close this issue now. Please feel free to open a new issue in case the issue still persists.
