### ISSUE TITLE
"Download the source from your desired release."

### ISSUE THREAD

**Issue by neilyoung** [quickbirdstudios/opencv-android#66]
Please clarify: Do you mean to download the OpenCV sources?

**Comment by nasirky** [comment]
@neilyoung Sorry for the late reply. It has been quite busy lately.

We want to upload all the source codes as releases and unfortunately, we haven't done it yet. However, We will try our best to upload them until end of April

**Comment by nasirky** [comment]
Sources for 3.4.X uploaded (check releases). 4.X.X is next

**Comment by nasirky** [comment]
Please see https://github.com/quickbirdstudios/opencv-android/issues/68
