### ISSUE TITLE
FP 16 support in opencv 4.0.1

### ISSUE THREAD

**Issue by anilsathyan7** [quickbirdstudios/opencv-android#7]
Does the 4.0.1 version of opencv support 'CV_16F' formats for Mat objects.? The 4.0 alpha version seems to support this feature (https://opencv.org/opencv-4-0-alpha/). However this 4.0.1 java version does not seem to support this functionality, in general.

**Comment by sellmair** [comment]
Hey @anilsathyan7 
this repository is just building and packaging the OpenCV Android SDK. Maybe consider asking the question in the [OpenCV Forum](https://answers.opencv.org/questions/). 
Other than that: There are traces in version 4.0.1 of `CV_16F` in the native code, but none of them in the Java code.
