### ISSUE TITLE
Possible to create a 3.4.5 build?

### ISSUE THREAD

**Issue by eaaliprantis** [quickbirdstudios/opencv-android#8]
Good Evening,

I kept trying to create a 3.4.5 Gradle build and I have been having trouble with it (https://github.com/eaaliprantis/OpenCV-Gradle ) and I have been struggling to get it to compile in my project.

Is there any way that you guys can add 3.4.5 into the build and/or give assistance to set up for 3.4.5?

Thank you very much <3

**Comment by sellmair** [comment]
Version 3.4.5 should be online now for you! ☺️
