### ISSUE TITLE
opencv 4.1.0 + contrib?

### ISSUE THREAD

**Issue by giandifra** [quickbirdstudios/opencv-android#9]
Can you add opencv 4.1.0 + contrib modules? thanks

**Comment by sellmair** [comment]
Working on it. I think we can build it in the next weeks 👍

**Comment by jacobg** [comment]
Hi any update?

**Comment by iamareebjamal** [comment]
You can try this - https://jitpack.io/#iamareebjamal/opencv-android/4.1.1-pre-contrib

However, this is not exactly 4.1.0 + contrib. This contains some more commits from 4.1.1 pre release. Because the oldest package present on the build farm was from 24th June

**Comment by sellmair** [comment]
Version 4.1.0 with contribution packages should be available now:
`com.quickbirdstudios:opencv:4.1.0-contrib`
